sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    

    - sudo apt-get install imagemagick 
    - sudo apt install ghostscript
    
    - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"

    - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
    - sudo apt install p7zip-full
    - 7z x web_log.tsv.7z

script:
 
  - bash shell/image.sh -h  

  - bash shell/image.sh -q 50% ./img
 
  - bash shell/image.sh -p 50% ./img

  - bash shell/image.sh -w hello ./img

  - bash shell/image.sh -r head h ./img

  - bash shell/image.sh -r tail h ./img

  - bash shell/image.sh -t ./img
  
 
  - bash shell/world.sh
  
  
  - bash shell/web.sh -h
 
  - bash shell/web.sh -a
 
  - bash shell/web.sh -b
 
  - bash shell/web.sh -c
 
  - bash shell/web.sh -d

  - bash shell/web.sh -e

  - bash shell/web.sh -u /pub/winvn/readme.txt
  
  
after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never